### PR TITLE
Update to Phalcon 3.0.x

### PR DESCRIPTION
**Pull request by naaness**
I can use phalcon eye on phalcon 3.0.1, please review my work, thanks a lot!!

### CODE REVIEW

**Comment by WooDzu** [comment]
@naaness this is great to see! I left some notes after reviewing the PR.

The CI tests are current failing and I will try to fix them some time today.

**Comment by lantian** [comment]
Hi. Thanks for your work. I will review it complitly. But it seems that I will need to merge it manual. Coz i already moved phalconeye to 3.0.1 version. And currently it is under huge refactoring. Still not pushed.

**Comment by naaness** [comment]
@WooDzu thanks man. @lantian  that is a good idea :)

**Comment by lantian** [comment]
Thanks, added some changes manually via 2929f098be3cea62df233ce2d6181e9aafd5611d.

**Pull request closed without merging**
